### ISSUE TITLE
Chronos performance drop between release-63 and release-72

### ISSUE THREAD

**Issue by mirw** [Metaswitch/chronos#136]
From https://github.com/Metaswitch/ralf/issues/155, according to @plfrancis:

> Ralf capacity (single instance) measured for release-63 was 105 CPS and 115 CPS for 5 minute and 30 minute registration scenarios respectively (15,000 subscribers). In release-72 these numbers have dropped to 55 CPS and 70 CPS.respectively.

> A 25 CPS traffic run was used to exercise a single Ralf VM (5000 subs, 5 minute registration). For release-73 the CPU reported by top on the Ralf VM was: ralf 28%, chronos 14%, memcached 1%. For release-63 the results were: ralf 16%, chronos 2%, memcached 0.7%.

So between release-63 and release-72, for a 25 CPS run, Chronos CPU usage grew from 2% to 14%.

The most significant change we've made in this period is Chronos resynchronization.  @eleanor-merry, as you're the expert on this, please can you take a look?

**Comment by graemerobertson** [comment]
Phil, do you know if the version of Chronos you were running had (or may have had) SAS compression turned on? Just to be clear, I'm talking about whether the version of sas-client compiled **with Chronos** contained this commit - https://github.com/Metaswitch/sas-client/commit/07459c295b0fc5a04027ee1b43b585d4c17aa7ce. Chronos doesn't actually log to SAS, but we currently create some SAS events in cpp-common (and then presumably drop them).

I've been looking at Chronos with and without compression turned on and CPU usage is about 50% higher with it turned on (which is nowhere near as high as the numbers you're seeing, although this could at least in part be due to the different scenarios we're running...). Either way, I'm working on a fix (which involves Chronos not doing any of the work to create or compress SAS events) and it'll almost certainly be worth retesting with the fix. I'll have it early tomorrow.

**Comment by graemerobertson** [comment]
Also, for completeness, that's the only performance difference I've been able to find from my performance testing of a single Ralf instance in Chronos from (roughly) release 63 to today.

**Comment by graemerobertson** [comment]
@plfrancis can you retest Chronos with https://github.com/Metaswitch/chronos/pull/138/files and https://github.com/Metaswitch/cpp-common/pull/307?

**Comment by plfrancis** [comment]
CPU reported by top on the Ralf VM for CCv7 at the loading specified above is: ralf 31%, chronos 13%, memcached 1.7%. Given performance numbers for CCv7 have been documented and considered sufficient for release, I'm closing this issue..
