### ISSUE TITLE
make full_test doesn't run again after a failure

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/chronos#210]
After hitting https://github.com/Metaswitch/chronos/issues/209 and installing the system libcares, `make full_test` kept failing with this error:

```
$ make full_test
Error: some memory errors have been detected
InvalidJump
See build/chronos_test/valgrind_output.xml for further details.
make: *** [valgrind_check_chronos_test] Error 2
```

This continued until I ran `make -B full_test` which recompiled and reran the test.

**Comment by bossmc** [comment]
I'm not sure I care too much, the alternative is that `make full_test` runs all the tests + all the valgrind tests every time it's invoked, even if the result isn't going to change.  Your situation is weird in that the change you made to resolve the build breakage was system-wide rather than specific to the codebase (which would have been picked up by running `make full_test` correctly).

**Comment by rkd-msw** [comment]
Would it run again after a success? I'm nervous that this will make it harder to track down intermittent failures by running the tests repeatedly - and actually, I think `make full_test` is an imperative command ("I want to run the tests") not a declarative command ("I want to get into the state where the tests have been run for these source files").

**Comment by bossmc** [comment]
No, `make full_test` is idempotent, `make test` is not (to allow one to track down a failing test) and `make valgrind_raw` is obviously not.

It's possible that `make X_check` should delete the input file if it fails, to force the tests to be re-run next time, but any product code fixes applied will cause a re-build + re-run automatically (again, your case was weird in that the fix was external to the product).

**Comment by rkd-msw** [comment]
Fine.
