### ISSUE TITLE
Data reliability, persistence mechanism

### ISSUE THREAD

**Issue by goelhimanshu** [Metaswitch/chronos#294]
I've gone through the documentation of Chronos, looks like Chronos keeps data in memory only (at the master and replica nodes). Our concern is a bit related to reliability of timers, in case master and replica nodes of a timer goes down due to some hardware issues. The Timer won't be able to pop once the nodes are recovered. Is there any way to use and persistence store or way to keep data on disk, so that it can be recovered in case of failures.

**Comment by graemerobertson** [comment]
I'm afraid we don't provide any mechanism for writing the timers to persistent storage. We use Chronos primarily for relatively short-lived timers and so it didn't make sense to use persistent storage (given that often the timer should have popped by the time the problem has been resolved), especially given the extra performance cost of writing data to disk. Similarly, Chronos is designed for use in the cloud where we'd normally expect a hardware failure to result in a completely new virtual machine being commissioned.

Does that make sense?

**Comment by goelhimanshu** [comment]
Thanks Graemerobertson, I have one more query related to replication of timers.
All timers created on a node will be replicated on the same set of replicas or will be replicated on different nodes for different timers created on the same node?
And if a node goes down, will replica node tries to replicate it to some other node to maintain the replication factor of that timer?

**Comment by eleanor-merry** [comment]
Hi @goelhimanshu.

Different timers created on the same node will have different replicas. The replicas for a timer are determined from the timer ID and the current list of Chronos nodes. We've got more information about replica selection at https://github.com/Metaswitch/chronos/blob/dev/doc/design/hashing.md.

If a node goes down then Chronos won't try and pick a new replica - while the node is down there is a loss of timer redundancy. When you (/your orchestration system) replace the node, then Chronos can then re-balance the timers to use the new node (so that all timers have the replication factor number of replicas, and all timers are evenly balanced across the nodes).

**Comment by eleanor-merry** [comment]
Closing this as answered
